"""Adicionado Usuario e Relacionamento

Revision ID: 42d31fcd6525
Revises: a2b249ec81db
Create Date: 2021-12-22 09:42:37.865588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d31fcd6525'
down_revision = 'a2b249ec81db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
