"""Testando

Revision ID: 839faeb82533
Revises: 42d31fcd6525
Create Date: 2021-12-22 14:03:40.464603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839faeb82533'
down_revision = '42d31fcd6525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
