"""Adicionado Usuario e Relacionamento

Revision ID: a2b249ec81db
Revises: 0e33753a45c2
Create Date: 2021-12-22 09:33:48.974421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b249ec81db'
down_revision = '0e33753a45c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produto', 'usuario', ['usuario_id'], ['id'])
    op.add_column('usuario', sa.Column('senha', sa.String(), nullable=True))
    op.drop_index('ix_usuario_telefone', table_name='usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_usuario_telefone', 'usuario', ['telefone'], unique=False)
    op.drop_column('usuario', 'senha')
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.drop_column('produto', 'usuario_id')
    # ### end Alembic commands ###
