"""Inicial

Revision ID: b80acf43e528
Revises: 
Create Date: 2021-12-21 23:08:04.272047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80acf43e528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_produto_nome'), 'produto', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produto_nome'), table_name='produto')
    # ### end Alembic commands ###
