"""Revisao geral

Revision ID: bf5c8c1eb48a
Revises: f6dbb53adee4
Create Date: 2021-12-29 13:24:35.660102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5c8c1eb48a'
down_revision = 'f6dbb53adee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
